import turtle 

finn = turtle.clone() 
finn.shape('circle')
finn.color('white')
finn.bgcolor('purple')
tin = turtle.clone()
tin.shape('triangle')
tin.color("green")
finn.stamp()
finn.goto(0,150)
finn.color("yellow")
finn.goto(75,150)
finn.goto(75,0)
tin.penup()
tin.goto(75,0)
tin.pensize(10)
tin.pendown()
tin.goto (75,-150)
tin.goto(150,-150)
tin.color("blue")
tin.goto(150,0)

 turtle.mainloop()
